employees_data={
    1:{"name":'vivek',
    'age':25,
    "position":'Manager'  
    },
    2:{"name":'tejas',
    'age':22,
    "position":'student'  
    },
    3:{"name":'pragati',
    'age':24,
    "position":'developer'  
    },
    4:{"name":'prajwal',
    'age':25,
    "position":'Cook'  
    }
}